name: HACS Validate

on:
  push:
  pull_request:
  # schedule:
    # - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
            # Remove this 'ignore' key when you have added brand images 
            #   for your integration to https://github.com/home-assistant/brands
          ignore: brands

